% Washing Machine Cycle Time Predictor via Fuzzy Logic
% Run this file using MATLAB.

% 1. Create a new Fuzzy Inference System (Mamdani type)
fis = newfis('WashingMachinePredictor', 'FISType', 'mamdani');

% 2. Add Inputs
% Dirt Level
fis = addvar(fis, 'input', 'DirtLevel', [0 100]);
fis = addmf(fis, 'input', 1, 'Low', 'trimf', [0 0 50]);
fis = addmf(fis, 'input', 1, 'Medium', 'trimf', [0 50 100]);
fis = addmf(fis, 'input', 1, 'High', 'trimf', [50 100 100]);

% Load Size
fis = addvar(fis, 'input', 'LoadSize', [0 100]);
fis = addmf(fis, 'input', 2, 'Small', 'trimf', [0 0 50]);
fis = addmf(fis, 'input', 2, 'Medium', 'trimf', [0 50 100]);
fis = addmf(fis, 'input', 2, 'Large', 'trimf', [50 100 100]);

% 3. Add Output
% Cycle Time
fis = addvar(fis, 'output', 'CycleTime', [0 120]);
fis = addmf(fis, 'output', 1, 'Short', 'trimf', [0 0 40]);
fis = addmf(fis, 'output', 1, 'Medium', 'trimf', [20 60 100]);
fis = addmf(fis, 'output', 1, 'Long', 'trimf', [80 120 120]);

% 4. Define Rules
% [Input1 Input2 Output1 Weight Connection]
% Connections: 1 stands for AND, 2 stands for OR
% Rule 1: IF Dirt is Low and Load is Small THEN Time is Short
% Rule 2: IF Dirt is Low and Load is Medium THEN Time is Medium
% Rule 3: IF Dirt is Low and Load is Large THEN Time is Medium
% Rule 4: IF Dirt is Medium and Load is Small THEN Time is Medium
% Rule 5: IF Dirt is Medium and Load is Medium THEN Time is Medium
% Rule 6: IF Dirt is Medium and Load is Large THEN Time is Long
% Rule 7: IF Dirt is High and Load is Small THEN Time is Medium
% Rule 8: IF Dirt is High and Load is Medium THEN Time is Long
% Rule 9: IF Dirt is High and Load is Large THEN Time is Long

rules = [
    1 1 1 1 1;
    1 2 2 1 1;
    1 3 2 1 1;
    2 1 2 1 1;
    2 2 2 1 1;
    2 3 3 1 1;
    3 1 2 1 1;
    3 2 3 1 1;
    3 3 3 1 1
];

fis = addrule(fis, rules);

% 5. Plottings (For Visualization in MATLAB)
figure('Name', 'Membership Function: Dirt Level');
plotmf(fis, 'input', 1);

figure('Name', 'Membership Function: Load Size');
plotmf(fis, 'input', 2);

figure('Name', 'Membership Function: Cycle Time');
plotmf(fis, 'output', 1);

% Generate Surface Viewer
figure('Name', 'Surface Viewer');
gensurf(fis);

% Display interactive Rule Viewer
ruleview(fis);

disp('Fuzzy Logic System Loaded!');
disp('You can inspect the 3D surface and rule viewer generated by the script!');
